version: "3"

services:
  discord-musicbot:
    build: .
    environment:
      - DISCORD_TOKEN=$DISCORD_TOKEN
      - COOKIE_SECRET=$COOKIE_SECRET
      - SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
      - DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
    image: discord-musicbot:latest
    container_name: discord-musicbot
    restart: unless-stopped
    networks:
      - lavalink-net
    depends_on:
      - lavalink
    volumes:
      - ./botconfig.js:/usr/src/app/botconfig.js:ro

  lavalink:
    image: fredboat/lavalink:3.7.5
    container_name: music-lavalink
    hostname: lavalink
    restart: unless-stopped
    networks:
      - lavalink-net
    volumes:
      - ./docker/application.yml:/opt/Lavalink/application.yml:ro

networks:
  lavalink-net:
